version: "3" #versao docker-compose

services: 
  base:
    build: 
      context: .
      dockerfile: Dockerfile
    image: base_image 

  bash:
    image: base_image
    user: root
    volumes: 
      - .:/usr/app/
    working_dir: /usr/app/
    entrypoint: /bin/sh