version: "3" #versao docker-compose

services: 
  base:
    build: 
      context: .
      dockerfile: Dockerfile
    image: base_image 

  bash:
    image: base_image
    user: root
    volumes: 
      - .:/usr/app/
    working_dir: /usr/app/
    entrypoint: /bin/sh

  python3:
    image: base_image
    user: root
    volumes: 
      - .:/usr/app/
    working_dir: /usr/app/
    command: "python3"

  jupyter:
    image: base_image
    user: root
    volumes: 
      - .:/usr/app/
    working_dir: /usr/app/
    command: "jupyter lab --ip=0.0.0.0  --port=8888 --allow-root --no-browser"
    ports: 
      - 8888:8888

  test:
    image: base_image
    user: root
    volumes:
      - .:/usr/app/
    working_dir: /usr/app/
    command: "pytest"