[package]
name = "greenhouse"
version = "0.0.5"
authors = ["Dauberson Mól <dauberson.mol@alumo.ufop.edu.br>"]
description = "A Python containerized framework for a better Data X development workflow."
repository = "https://github.com/dauberson/py-greenhouse"
license = "Apache-2.0"